In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('../data/raw/manual_spreadsheet/Copia de vendas sorvete.xlsx', sheet_name='Dezembro 23', header=2)

In [3]:
df.head()

  Unnamed: 0  Vendas   Gastos Unnamed: 3 Unnamed: 4  Unnamed: 5
0        NaN     NaN  2614.79  Cartao Nu   Dinheiro         NaN
1          2  1375.0    99.38        Luz        Pix         NaN
2          3   752.0    87.97        Luz     Cartao         NaN
3          4   219.0       21        NaN        NaN         0.0
4          5   827.0      NaN        NaN        NaN         NaN

In [4]:
df['Unnamed: 0'] = pd.to_numeric(df['Unnamed: 0'], errors='coerce')

In [5]:
df.head()

   Unnamed: 0  Vendas   Gastos Unnamed: 3 Unnamed: 4  Unnamed: 5
0         NaN     NaN  2614.79  Cartao Nu   Dinheiro         NaN
1         2.0  1375.0    99.38        Luz        Pix         NaN
2         3.0   752.0    87.97        Luz     Cartao         NaN
3         4.0   219.0       21        NaN        NaN         0.0
4         5.0   827.0      NaN        NaN        NaN         NaN

In [6]:
df.dropna(subset=['Unnamed: 0'], inplace=True)

In [7]:
df.tail(5)

    Unnamed: 0  Vendas Gastos Unnamed: 3 Unnamed: 4  Unnamed: 5
26        27.0   926.0    NaN        NaN        NaN         NaN
27        28.0   936.0    NaN        NaN        NaN         NaN
28        29.0   533.0    NaN        NaN        NaN         NaN
29        30.0  1266.0    NaN        NaN        NaN         NaN
30        31.0     0.0    NaN        NaN        NaN         NaN

In [8]:
df.rename(columns={'Unnamed: 0': 'day', 'Vendas': 'sales', 'Gastos': 'expenses', 'Unnamed: 3': 'expense_category'}, inplace=True)

In [9]:
df.columns

Index(['day', 'sales', 'expenses', 'expense_category', 'Unnamed: 4',
       'Unnamed: 5'],
      dtype='str')

In [10]:
df= df[['day', 'sales', 'expenses', 'expense_category']]

In [11]:
df.columns

Index(['day', 'sales', 'expenses', 'expense_category'], dtype='str')

In [12]:
df.head(10)

     day   sales expenses expense_category
1    2.0  1375.0    99.38              Luz
2    3.0   752.0    87.97              Luz
3    4.0   219.0       21              NaN
4    5.0   827.0      NaN              NaN
5    6.0   837.0    242.7            Stock
6    7.0     0.0   236.96            Stock
7    8.0   978.0    88.15             Agua
8    9.0  1781.0    75.81             Coco
9   10.0   664.0    119.7             Coco
10  11.0   806.0     11.2              NaN

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 1 to 30
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   day               30 non-null     float64
 1   sales             30 non-null     float64
 2   expenses          9 non-null      object
 3   expense_category  7 non-null      str
dtypes: float64(2), object(1), str(1)
memory usage: 1.1+ KB

In [14]:
df['expenses'].apply(type).unique()

array([<class 'float'>, <class 'int'>], dtype=object)

In [15]:
df['expenses'] = pd.to_numeric(df['expenses'], errors='coerce')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 1 to 30
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   day               30 non-null     float64
 1   sales             30 non-null     float64
 2   expenses          9 non-null      float64
 3   expense_category  7 non-null      str
dtypes: float64(3), str(1)
memory usage: 1.1 KB

In [17]:
def clean_old_format(sheet_name):
    df = pd.read_excel('../data/raw/manual_spreadsheet/Copia de vendas sorvete.xlsx', sheet_name=sheet_name, header= None)
    header_row = df[df[1] == 'Vendas'].index[0]
    df = pd.read_excel('../data/raw/manual_spreadsheet/Copia de vendas sorvete.xlsx', sheet_name=sheet_name, header=header_row)
    df['Unnamed: 0'] = pd.to_numeric(df['Unnamed: 0'], errors='coerce')
    df.dropna(subset=['Unnamed: 0'], inplace=True)
    df.rename(columns={'Unnamed: 0': 'day', 'Vendas': 'sales', 'Gastos': 'expenses', 'Unnamed: 3': 'expense_category'}, inplace=True)
    df= df[['day', 'sales', 'expenses', 'expense_category']]
    df['expenses'] = pd.to_numeric(df['expenses'], errors='coerce')
    df['month_sheet'] = sheet_name
    return df

In [18]:
xls = pd.ExcelFile('../data/raw/manual_spreadsheet/Copia de vendas sorvete.xlsx')
print(xls.sheet_names)

['Anual', 'Aug 26', 'Jul 26', 'Jun 26', 'May 26', 'April 26', 'March 26', 'February 26', 'January 26', 'Dezembro 25', 'Novembro 25', 'Outubro 25', 'Setembro 25', 'Agosto 25', 'Julho 25', 'Junho 25', 'Maio 25', 'Abril 25', 'Mar 25', 'Fev 25', 'Jan 25', 'Dez 24', 'Nov 24', 'Outubro 24', 'Setembro 24', 'Agosto 24', 'Julho 24', 'Junho 24', 'Maio 24', 'Abril 24', 'Março 24', 'Fevereiro 24', 'Janeiro 24 ', 'Dezembro 23', 'Novembro 23', 'Outubro 23', 'Setembro 23', 'Agosto 23', 'Julho 23', 'Junho 23', 'Maio 23', 'Abril 23', 'Março 23', 'Fevereiro 23', 'Janeiro 23', 'Dezembro 22', 'Novembro 22']

In [19]:
old_format_sheets = list(xls.sheet_names)
old_format_sheets.remove('Anual')
old_format_sheets.remove('Novembro 22')
old_format_sheets.remove('April 26')
old_format_sheets.remove('May 26')
old_format_sheets.remove('Jun 26')
old_format_sheets.remove('Jul 26')
old_format_sheets.remove('Aug 26')

In [20]:
print(len(old_format_sheets))
print(old_format_sheets)

40
['March 26', 'February 26', 'January 26', 'Dezembro 25', 'Novembro 25', 'Outubro 25', 'Setembro 25', 'Agosto 25', 'Julho 25', 'Junho 25', 'Maio 25', 'Abril 25', 'Mar 25', 'Fev 25', 'Jan 25', 'Dez 24', 'Nov 24', 'Outubro 24', 'Setembro 24', 'Agosto 24', 'Julho 24', 'Junho 24', 'Maio 24', 'Abril 24', 'Março 24', 'Fevereiro 24', 'Janeiro 24 ', 'Dezembro 23', 'Novembro 23', 'Outubro 23', 'Setembro 23', 'Agosto 23', 'Julho 23', 'Junho 23', 'Maio 23', 'Abril 23', 'Março 23', 'Fevereiro 23', 'Janeiro 23', 'Dezembro 22']

In [21]:
monthly_dfs = []
for sheet in old_format_sheets:
    monthly_dfs.append(clean_old_format(sheet))

In [22]:
print(len(monthly_dfs))

40

In [23]:
monthly_dfs[0].head()

   day  sales  expenses expense_category month_sheet
0  1.0    844    5176.0           Cartao    March 26
1  2.0    321       NaN              NaN    March 26
2  3.0    414       NaN              NaN    March 26
3  4.0    486     616.0              Luz    March 26
4  5.0    336      85.0              Das    March 26

In [24]:
daily_sales_history = pd.concat(monthly_dfs, ignore_index=True)

In [25]:
daily_sales_history.shape

(1204, 5)

In [26]:
daily_sales_history.head()

   day  sales  expenses expense_category month_sheet
0  1.0  844.0    5176.0           Cartao    March 26
1  2.0  321.0       NaN              NaN    March 26
2  3.0  414.0       NaN              NaN    March 26
3  4.0  486.0     616.0              Luz    March 26
4  5.0  336.0      85.0              Das    March 26

In [27]:
daily_sales_history.tail()

       day  sales  expenses expense_category  month_sheet
1199  27.0  734.0       NaN              NaN  Dezembro 22
1200  28.0  738.0       NaN              NaN  Dezembro 22
1201  29.0  700.0       NaN              NaN  Dezembro 22
1202  30.0  796.0       NaN              NaN  Dezembro 22
1203  31.0  667.0    2680.0              NaN  Dezembro 22

In [28]:

datas_geradas = pd.date_range(start='2026-03-31', periods=40, freq='-1ME')
print(datas_geradas)

DatetimeIndex(['2026-03-31', '2026-02-28', '2026-01-31', '2025-12-31',
               '2025-11-30', '2025-10-31', '2025-09-30', '2025-08-31',
               '2025-07-31', '2025-06-30', '2025-05-31', '2025-04-30',
               '2025-03-31', '2025-02-28', '2025-01-31', '2024-12-31',
               '2024-11-30', '2024-10-31', '2024-09-30', '2024-08-31',
               '2024-07-31', '2024-06-30', '2024-05-31', '2024-04-30',
               '2024-03-31', '2024-02-29', '2024-01-31', '2023-12-31',
               '2023-11-30', '2023-10-31', '2023-09-30', '2023-08-31',
               '2023-07-31', '2023-06-30', '2023-05-31', '2023-04-30',
               '2023-03-31', '2023-02-28', '2023-01-31', '2022-12-31'],
              dtype='datetime64[us]', freq='-1ME')

In [29]:
sheet_date_pairs = list(zip(old_format_sheets, datas_geradas))

In [30]:
print(sheet_date_pairs[:5])

[('March 26', Timestamp('2026-03-31 00:00:00')), ('February 26', Timestamp('2026-02-28 00:00:00')), ('January 26', Timestamp('2026-01-31 00:00:00')), ('Dezembro 25', Timestamp('2025-12-31 00:00:00')), ('Novembro 25', Timestamp('2025-11-30 00:00:00'))]

In [31]:
sheet_to_date = dict(sheet_date_pairs)

In [32]:
print(sheet_to_date['Dezembro 22'])

2022-12-31 00:00:00

In [33]:
daily_sales_history['month_year'] = daily_sales_history['month_sheet'].map(sheet_to_date)

In [34]:
daily_sales_history.head()
daily_sales_history.tail()

       day  sales  expenses expense_category  month_sheet month_year
1199  27.0  734.0       NaN              NaN  Dezembro 22 2022-12-31
1200  28.0  738.0       NaN              NaN  Dezembro 22 2022-12-31
1201  29.0  700.0       NaN              NaN  Dezembro 22 2022-12-31
1202  30.0  796.0       NaN              NaN  Dezembro 22 2022-12-31
1203  31.0  667.0    2680.0              NaN  Dezembro 22 2022-12-31

In [35]:
daily_sales_history['date'] = pd.to_datetime(daily_sales_history['day'].astype(int).astype(str) + '-' + daily_sales_history['month_year'].dt.strftime('%m-%Y'), format='%d-%m-%Y', errors='coerce')

In [36]:
daily_sales_history[['day', 'month_year', 'date']].head(10)

    day month_year       date
0   1.0 2026-03-31 2026-03-01
1   2.0 2026-03-31 2026-03-02
2   3.0 2026-03-31 2026-03-03
3   4.0 2026-03-31 2026-03-04
4   5.0 2026-03-31 2026-03-05
5   6.0 2026-03-31 2026-03-06
6   7.0 2026-03-31 2026-03-07
7   8.0 2026-03-31 2026-03-08
8   9.0 2026-03-31 2026-03-09
9  10.0 2026-03-31 2026-03-10

In [37]:
daily_sales_history.isna().sum()

day                    0
sales                  1
expenses             990
expense_category    1027
month_sheet            0
month_year             0
date                   2
dtype: int64

In [38]:
print(daily_sales_history['date'].min())
print(daily_sales_history['date'].max())

2022-12-01 00:00:00
2026-03-31 00:00:00

In [39]:
daily_sales_history[daily_sales_history['date'].isna()]

        day  sales  expenses expense_category month_sheet month_year date
728   270.0    NaN       NaN              NaN    Abril 24 2024-04-30  NaT
1033   31.0    0.0       NaN              NaN    Junho 23 2023-06-30  NaT

In [40]:
daily_sales_history.drop([728, 1033], inplace=True)

In [41]:
daily_sales_history.isna().sum()

day                    0
sales                  0
expenses             988
expense_category    1025
month_sheet            0
month_year             0
date                   0
dtype: int64

In [42]:
monthly_expenses = daily_sales_history[['date','expenses', 'expense_category']]
revenue = daily_sales_history[['date','sales']]

In [43]:
monthly_expenses.head()

        date  expenses expense_category
0 2026-03-01    5176.0           Cartao
1 2026-03-02       NaN              NaN
2 2026-03-03       NaN              NaN
3 2026-03-04     616.0              Luz
4 2026-03-05      85.0              Das

In [44]:
revenue.head()

        date  sales
0 2026-03-01  844.0
1 2026-03-02  321.0
2 2026-03-03  414.0
3 2026-03-04  486.0
4 2026-03-05  336.0

In [45]:
monthly_expenses = daily_sales_history.groupby(['month_year', 'expense_category']).agg({'expenses': 'sum'}).reset_index()

In [46]:
monthly_expenses.head()

  month_year expense_category  expenses
0 2022-12-31         10cx lt     488.00
1 2022-12-31       50tp 500ml      7.30
2 2022-12-31        7cx leite    348.00
3 2022-12-31         Atacadao    194.82
4 2022-12-31          Açucar     115.02

In [47]:
daily_sales_history['expense_category'].nunique()

49

In [48]:
print(daily_sales_history['expense_category'].unique())

<StringArray>
[          'Cartao',                nan,              'Luz',
              'Das',           'Contab',     'Restaurante ',
         'Mercado ',          'Faltou ',           'Cartão',
         'Boleto  ',            'Leite',           'Bancos',
         'Maq chur',           'Farol ',          'Cartao ',
            'Kouth',             'Guia',        'Cartao Nu',
        'Papel crê',             'Coco',     'Cartao inter',
             'Agua',        'Cartão Nu',           'Alvara',
               'Ss',            'Laine',            'Stock',
             'Luz ',             'S.S.',          'Sacolas',
        'Cartao NU',       'Shopping s',         'Cartão N',
           'Diesel',         'Freezer ',         'Cartão A',
         'Recheio ',            'Óleo ',             'Pneu',
   'Atacadao+ Maxi', 'Stock (Acucar+L)',      'D Aparecida',
          'Diesel ',        '7cx leite',       '50tp 500ml',
         'Atacadao',      'Stock agua ',          'Açucar ',
         '10cx lt ',     'S sorveteiro']
Length: 50, dtype: str

In [49]:
daily_sales_history['expense_category'] = daily_sales_history['expense_category'].str.strip()

In [50]:
print(daily_sales_history['expense_category'].unique())

<StringArray>
[          'Cartao',                nan,              'Luz',
              'Das',           'Contab',      'Restaurante',
          'Mercado',           'Faltou',           'Cartão',
           'Boleto',            'Leite',           'Bancos',
         'Maq chur',            'Farol',            'Kouth',
             'Guia',        'Cartao Nu',        'Papel crê',
             'Coco',     'Cartao inter',             'Agua',
        'Cartão Nu',           'Alvara',               'Ss',
            'Laine',            'Stock',             'S.S.',
          'Sacolas',        'Cartao NU',       'Shopping s',
         'Cartão N',           'Diesel',          'Freezer',
         'Cartão A',          'Recheio',             'Óleo',
             'Pneu',   'Atacadao+ Maxi', 'Stock (Acucar+L)',
      'D Aparecida',        '7cx leite',       '50tp 500ml',
         'Atacadao',       'Stock agua',           'Açucar',
          '10cx lt',     'S sorveteiro']
Length: 47, dtype: str

In [51]:
category_mapping = {'Cartao': 'Cartao', 'Cartão': 'Cartao', 'Cartao Nu': 'Cartao', 'Cartão N': 'Cartao', 'Cartao NU': 'Cartao', 'Cartao N': 'Cartao', 'Cartão A': 'Cartao', 'Cartao inter': 'Cartao'}

In [52]:
daily_sales_history['expense_category'] = daily_sales_history['expense_category'].replace(category_mapping)

In [53]:
daily_sales_history['expense_category'].unique()

<StringArray>
[          'Cartao',                nan,              'Luz',
              'Das',           'Contab',      'Restaurante',
          'Mercado',           'Faltou',           'Boleto',
            'Leite',           'Bancos',         'Maq chur',
            'Farol',            'Kouth',             'Guia',
        'Papel crê',             'Coco',             'Agua',
        'Cartão Nu',           'Alvara',               'Ss',
            'Laine',            'Stock',             'S.S.',
          'Sacolas',       'Shopping s',           'Diesel',
          'Freezer',          'Recheio',             'Óleo',
             'Pneu',   'Atacadao+ Maxi', 'Stock (Acucar+L)',
      'D Aparecida',        '7cx leite',       '50tp 500ml',
         'Atacadao',       'Stock agua',           'Açucar',
          '10cx lt',     'S sorveteiro']
Length: 41, dtype: str

In [54]:
grocery_categories = {'Mercado': 'Mercado', 'Leite': 'Mercado', 'Coco': 'Mercado', 'Agua': 'Mercado', 'Stock': 'Mercado', 'Shopping s': 'Mercado', 'Recheio': 'Mercado', 'Atacadao+ Maxi': 'Mercado', 'Stock (Acucar+L)': 'Mercado', 'D Aparecida': 'Mercado', '7cx leite': 'Mercado', '50tp 500ml': 'Mercado', 'Atacadao': 'Mercado', 'Stock agua': 'Mercado', 'Açucar': 'Mercado', '10cx lt': 'Mercado', 'S sorveteiro': 'Mercado', 'Ss': 'Mercado', 'S.S.': 'Mercado', 'Boleto': 'Mercado', 'Papel crê': 'Mercado', 'Óleo': 'Mercado', 'Sacolas': 'Mercado'}

In [55]:
daily_sales_history['expense_category'] = daily_sales_history['expense_category'].replace(grocery_categories)

In [56]:
daily_sales_history['expense_category'].unique()

<StringArray>
[     'Cartao',           nan,         'Luz',         'Das',      'Contab',
 'Restaurante',     'Mercado',      'Faltou',      'Bancos',    'Maq chur',
       'Farol',       'Kouth',        'Guia',   'Cartão Nu',      'Alvara',
       'Laine',      'Diesel',     'Freezer',        'Pneu']
Length: 19, dtype: str

In [57]:
gastos_veiculo = {'Farol': 'veiculo', 'Kouth': 'veiculo', 'Pneu': 'veiculo', 'Diesel': 'veiculo'}

In [58]:
daily_sales_history['expense_category'] = daily_sales_history['expense_category'].replace(gastos_veiculo)

In [59]:
daily_sales_history['expense_category'].unique()

<StringArray>
[     'Cartao',           nan,         'Luz',         'Das',      'Contab',
 'Restaurante',     'Mercado',      'Faltou',      'Bancos',    'Maq chur',
     'veiculo',        'Guia',   'Cartão Nu',      'Alvara',       'Laine',
     'Freezer']
Length: 16, dtype: str

In [60]:
daily_sales_history['expense_category'].notna().sum()

np.int64(177)

In [61]:
daily_sales_history['expenses'].notna().sum()

np.int64(214)

In [62]:
daily_sales_history.loc[daily_sales_history['expenses'].notna() & daily_sales_history['expense_category'].isna(), 'expense_category'] = 'Outros'

In [63]:
daily_sales_history['expense_category'].notna().sum()

np.int64(225)

In [64]:
daily_sales_history['expenses'].notna().sum()

np.int64(214)

In [65]:
daily_sales_history.duplicated().sum()

np.int64(0)

In [66]:
daily_sales_history.shape

(1202, 7)

In [67]:
daily_sales_history[daily_sales_history['expenses'].isna() & daily_sales_history['expense_category'].notna()]

,day,sales,expenses,expense_category,month_sheet,month_year,date
7,8.0,264.0,NaN,Mercado,March 26,2026-03-31,2026-03-08
10,11.0,264.0,NaN,Faltou,March 26,2026-03-31,2026-03-11
38,8.0,1319.0,NaN,Mercado,February 26,2026-02-28,2026-02-08
92,3.0,700.0,NaN,Cartao,Dezembro 25,2025-12-31,2025-12-03
123,3.0,557.0,NaN,Cartao,Novembro 25,2025-11-30,2025-11-03
974,3.0,194.0,NaN,veiculo,Julho 23,2023-07-31,2023-07-03
975,4.0,79.0,NaN,Luz,Julho 23,2023-07-31,2023-07-04
1005,3.0,555.0,NaN,veiculo,Junho 23,2023-06-30,2023-06-03
1006,4.0,324.0,NaN,Luz,Junho 23,2023-06-30,2023-06-04
1036,3.0,0.0,NaN,veiculo,Maio 23,2023-05-31,2023-05-03
1068,6.0,0.0,NaN,veiculo,Abril 23,2023-04-30,2023-04-06

In [68]:
daily_sales_history.loc[daily_sales_history['expenses'].isna() & daily_sales_history['expense_category'].notna(), 'expense_category'] = None

In [69]:

daily_sales_history['expenses'].notna().sum()

np.int64(214)

In [70]:
daily_sales_history['expense_category'].notna().sum()

np.int64(214)

In [71]:
monthly_expenses = daily_sales_history.groupby(['month_year', 'expense_category']).agg({'expenses': 'sum'}).reset_index()

In [72]:
monthly_expenses.head()

  month_year expense_category  expenses
0 2022-12-31          Mercado   2670.62
1 2022-12-31           Outros   3192.62
2 2022-12-31          veiculo    105.00
3 2023-01-31              Luz     75.00
4 2023-01-31          Mercado    766.85

In [73]:
monthly_expenses.shape

(151, 3)

In [74]:
monthly_expenses.to_csv('../data/processed/monthly_expenses.csv', index=False)

In [75]:
revenue.columns

Index(['date', 'sales'], dtype='str')

In [76]:
revenue.head()

        date  sales
0 2026-03-01  844.0
1 2026-03-02  321.0
2 2026-03-03  414.0
3 2026-03-04  486.0
4 2026-03-05  336.0

In [77]:
revenue.to_csv('../data/processed/revenue.csv', index=False)

In [78]:
import os

In [79]:
print(os.listdir('../data/processed'))

['monthly_expenses.csv', 'revenue.csv', 'sales_detail.csv']

In [80]:
df_raw_new = pd.read_excel('../data/raw/manual_spreadsheet/Copia de vendas sorvete.xlsx', sheet_name='April 26', header=None)

In [81]:
df_raw_new.head(10)

                     0       1       2                    3         4     5
0                  NaN     NaN     NaN  2026-04-01 00:00:00       NaN   NaN
1                  NaN     NaN     NaN                  NaN       NaN   NaN
2                 Data  Vendas  Gastos          Tipo gasto   Dinheiro   NaN
3  2026-04-01 00:00:00     500    4125               Cartao       Pix   NaN
4  2026-04-02 00:00:00     700     296               Boleto    Cartao   NaN
5  2026-04-03 00:00:00    1330     NaN                  NaN       NaN -50.0
6  2026-04-04 00:00:00    1671     748                  Luz       NaN   NaN
7  2026-04-05 00:00:00       0      89                  Das       NaN   NaN
8  2026-04-06 00:00:00     625     100               Contab       NaN   NaN
9  2026-04-07 00:00:00     334     233         Restaurante        NaN   NaN

In [82]:
def clean_new_format(sheet_name):
    df = pd.read_excel('../data/raw/manual_spreadsheet/Copia de vendas sorvete.xlsx', sheet_name=sheet_name, header=None)
    header_row = df[df[0] == 'Data'].index[0]
    df = pd.read_excel('../data/raw/manual_spreadsheet/Copia de vendas sorvete.xlsx', sheet_name=sheet_name, header=header_row)
    df.columns = df.columns.str.strip()
    df.rename(columns={'Data': 'date', 'Vendas': 'sales', 'Gastos': 'expenses', 'Tipo gasto': 'expense_category'}, inplace=True)
    df= df[['date', 'sales', 'expenses', 'expense_category']]
    df['expenses'] = pd.to_numeric(df['expenses'], errors='coerce')
    df['date'] = pd.to_datetime(df['date'], format='%d/%m/%Y', errors='coerce')
    df.dropna(subset=['date'], inplace=True)
    df['month_sheet'] = sheet_name
    return df

In [83]:
clean_new_format('April 26').head(10)

        date   sales  expenses expense_category month_sheet
0 2026-04-01   500.0    4125.0           Cartao    April 26
1 2026-04-02   700.0     296.0           Boleto    April 26
2 2026-04-03  1330.0       NaN              NaN    April 26
3 2026-04-04  1671.0     748.0              Luz    April 26
4 2026-04-05     0.0      89.0              Das    April 26
5 2026-04-06   625.0     100.0           Contab    April 26
6 2026-04-07   334.0     233.0     Restaurante     April 26
7 2026-04-08   454.0       NaN         Mercado     April 26
8 2026-04-09   373.0      50.0        Eletrica     April 26
9 2026-04-10   615.0       NaN              NaN    April 26

In [84]:
clean_new_format('May 26').head(10)

        date   sales  expenses expense_category month_sheet
0 2026-05-01   859.0    3744.0           Cartao      May 26
1 2026-05-02   116.0       NaN           Boleto      May 26
2 2026-05-03   521.0       NaN              NaN      May 26
3 2026-05-04   469.0     250.0              Luz      May 26
4 2026-05-05   344.0      89.0              Das      May 26
5 2026-05-06   292.0     107.0           Contab      May 26
6 2026-05-07   648.0     201.0     Restaurante       May 26
7 2026-05-08     0.0       NaN                       May 26
8 2026-05-09  1270.0       NaN              NaN      May 26
9 2026-05-10   298.0       NaN              NaN      May 26

In [85]:
clean_new_format('Jun 26').head(10)

        date   sales  expenses expense_category month_sheet
0 2026-06-01   332.0    4272.0           Cartao      Jun 26
1 2026-06-02   418.0       NaN           Boleto      Jun 26
2 2026-06-03   200.0       NaN              NaN      Jun 26
3 2026-06-04  1007.0     368.0              Luz      Jun 26
4 2026-06-05   583.0      89.0              Das      Jun 26
5 2026-06-06   774.0     107.0           Contab      Jun 26
6 2026-06-07   836.0     165.0     Restaurante       Jun 26
7 2026-06-08   526.0     150.0        Eletrica       Jun 26
8 2026-06-09   459.0       NaN              NaN      Jun 26
9 2026-06-10     0.0       NaN              NaN      Jun 26

In [86]:
clean_new_format('Jul 26').head(10)

        date   sales  expenses expense_category month_sheet
0 2026-07-01   625.0    3200.0           Cartao      Jul 26
1 2026-07-02   130.0       NaN           Boleto      Jul 26
2 2026-07-03   114.0       NaN              NaN      Jul 26
3 2026-07-04  1180.0     339.0              Luz      Jul 26
4 2026-07-05     0.0      89.0              Das      Jul 26
5 2026-07-06     0.0     107.0           Contab      Jul 26
6 2026-07-07   278.0      88.0     Restaurante       Jul 26
7 2026-07-08   711.0      50.0        Eletrica       Jul 26
8 2026-07-09   709.0       NaN              NaN      Jul 26
9 2026-07-10   477.0       NaN              NaN      Jul 26

In [87]:
new_format_sheets = ['April 26', 'May 26', 'Jun 26', 'Jul 26']
monthly_nf_dfs = []
for sheet in new_format_sheets:
    monthly_nf_dfs.append(clean_new_format(sheet))

daily_sales_history_nf = pd.concat(monthly_nf_dfs, ignore_index=True)

In [88]:
daily_sales_history_nf.shape

(122, 5)

In [89]:
daily_sales_history_nf.head()

        date   sales  expenses expense_category month_sheet
0 2026-04-01   500.0    4125.0           Cartao    April 26
1 2026-04-02   700.0     296.0           Boleto    April 26
2 2026-04-03  1330.0       NaN              NaN    April 26
3 2026-04-04  1671.0     748.0              Luz    April 26
4 2026-04-05     0.0      89.0              Das    April 26

In [90]:
print(daily_sales_history.columns)

Index(['day', 'sales', 'expenses', 'expense_category', 'month_sheet',
       'month_year', 'date'],
      dtype='str')

In [91]:
print(daily_sales_history_nf.columns)

Index(['date', 'sales', 'expenses', 'expense_category', 'month_sheet'], dtype='str')

In [92]:
daily_sales_history.drop(columns=['day', 'month_year'], inplace=True)

In [93]:
print(daily_sales_history.columns)

Index(['sales', 'expenses', 'expense_category', 'month_sheet', 'date'], dtype='str')

In [94]:
daily_sales_history.shape

(1202, 5)

In [95]:
daily_sales_history.head()

   sales  expenses expense_category month_sheet       date
0  844.0    5176.0           Cartao    March 26 2026-03-01
1  321.0       NaN              NaN    March 26 2026-03-02
2  414.0       NaN              NaN    March 26 2026-03-03
3  486.0     616.0              Luz    March 26 2026-03-04
4  336.0      85.0              Das    March 26 2026-03-05

In [96]:
daily_sales_history_nf.head()

        date   sales  expenses expense_category month_sheet
0 2026-04-01   500.0    4125.0           Cartao    April 26
1 2026-04-02   700.0     296.0           Boleto    April 26
2 2026-04-03  1330.0       NaN              NaN    April 26
3 2026-04-04  1671.0     748.0              Luz    April 26
4 2026-04-05     0.0      89.0              Das    April 26

In [97]:
daily_sales_history_full = pd.concat([daily_sales_history, daily_sales_history_nf], ignore_index=True)

In [98]:
daily_sales_history_full.shape

(1324, 5)

In [99]:
daily_sales_history_full.tail(10)

       sales  expenses expense_category month_sheet       date
1314     0.0       NaN              NaN      Jul 26 2026-07-22
1315   485.0       NaN              NaN      Jul 26 2026-07-23
1316   175.0       NaN              NaN      Jul 26 2026-07-24
1317  1188.0       NaN              NaN      Jul 26 2026-07-25
1318  1018.0       NaN              NaN      Jul 26 2026-07-26
1319   582.0       NaN              NaN      Jul 26 2026-07-27
1320   574.0       NaN              NaN      Jul 26 2026-07-28
1321   497.0       NaN              NaN      Jul 26 2026-07-29
1322   487.0       NaN              NaN      Jul 26 2026-07-30
1323   574.0       NaN              NaN      Jul 26 2026-07-31

In [100]:
daily_sales_history_full.rename(columns={'sales': 'revenue'}, inplace=True)
revenue = daily_sales_history_full[['date','revenue']]
daily_sales_history_full['month_year'] = daily_sales_history_full['date'].dt.to_period('M')
monthly_expenses = daily_sales_history_full.groupby(['month_year', 'expense_category']).agg({'expenses': 'sum'}).reset_index()

In [101]:
monthly_expenses.drop(monthly_expenses[monthly_expenses['expense_category'] == 'Faltou mês anterior  '].index, inplace=True)

In [102]:
monthly_expenses.to_csv('../data/processed/monthly_expenses.csv', index=False)
revenue.to_csv('../data/processed/revenue.csv', index=False)

In [103]:
print(os.listdir('../data/processed'))

['monthly_expenses.csv', 'revenue.csv', 'sales_detail.csv']

In [104]:
sales_2025 = pd.read_csv('../data/raw/kyte/Sales_20250101_20260101.csv')
sales_2025.head()

,Number,Status,Date/Time,Qty.,Total amount,Items Description,Subtotal,Discount,Sales tax,Delivery,Total,Profits,Payment Method,Customer,Salesperson,Observation
0,1-1,Sale,05/22/2025 2:53 PM,2,3,"1xCopo 150ml, 2xCasquinha",18.0,0.0,0,0,18.0,0.0,Débito,NaN,Lucas,NaN
1,2-1,Sale,05/22/2025 3:08 PM,1,3,3xCasquinha,18.0,0.0,0,0,18.0,0.0,Pix,NaN,Lucas,NaN
2,5-1,Sale,05/22/2025 4:05 PM,1,1,1xCasquinha,6.0,0.0,0,0,6.0,0.0,Efectivo,NaN,Lucas,NaN
3,6-1,Sale,05/22/2025 4:08 PM,2,2,"1xChurros de chocolate , 1xCasquinha",14.0,0.0,0,0,14.0,0.0,Crédito,NaN,Lucas,NaN
4,7-1,Sale,05/22/2025 4:12 PM,2,2,"1xChurros de chocolate , 1xChurros doce de leite",16.0,0.0,0,0,16.0,0.0,Crédito,NaN,Lucas,NaN

In [105]:
sales_detail = sales_2025[['Date/Time', 'Total', 'Payment Method']]

In [106]:
sales_detail.rename(columns={'Date/Time': 'sale_time', 'Total': 'amount_sold', 'Payment Method': 'payment_type'}, inplace=True)

In [107]:
sales_detail.head()

            sale_time  amount_sold payment_type
0  05/22/2025 2:53 PM         18.0       Débito
1  05/22/2025 3:08 PM         18.0          Pix
2  05/22/2025 4:05 PM          6.0     Efectivo
3  05/22/2025 4:08 PM         14.0      Crédito
4  05/22/2025 4:12 PM         16.0      Crédito

In [108]:
sales_2025.dtypes

Number                   str
Status                   str
Date/Time                str
Qty.                   int64
Total amount           int64
Items Description        str
Subtotal             float64
Discount             float64
Sales tax              int64
Delivery               int64
Total                float64
Profits              float64
Payment Method           str
Customer                 str
Salesperson              str
Observation              str
dtype: object

In [109]:
sales_detail['sale_time'] = pd.to_datetime(sales_detail['sale_time'], format='%m/%d/%Y %I:%M %p', errors='coerce')

In [110]:
sales_detail.dtypes

sale_time       datetime64[us]
amount_sold            float64
payment_type               str
dtype: object

In [111]:

sales_detail['sale_time'].isna().sum()

np.int64(0)

In [112]:

sales_detail.head()

            sale_time  amount_sold payment_type
0 2025-05-22 14:53:00         18.0       Débito
1 2025-05-22 15:08:00         18.0          Pix
2 2025-05-22 16:05:00          6.0     Efectivo
3 2025-05-22 16:08:00         14.0      Crédito
4 2025-05-22 16:12:00         16.0      Crédito

In [113]:
print(sales_detail['sale_time'].head())

0   2025-05-22 14:53:00
1   2025-05-22 15:08:00
2   2025-05-22 16:05:00
3   2025-05-22 16:08:00
4   2025-05-22 16:12:00
Name: sale_time, dtype: datetime64[us]

In [114]:
sales_detail['payment_type'].unique()

<StringArray>
[                         'Débito',                             'Pix',
                        'Efectivo',                         'Crédito',
                               nan,                  'Tarjeta Débito',
                 'Tarjeta Crédito', 'Tarjeta Débito, Tarjeta Crédito',
                  'Débito, Débito',       'Efectivo, Tarjeta Crédito',
        'Efectivo, Tarjeta Débito',                 'Venta a crédito',
             'Pix, Tarjeta Débito',              'Efectivo, Efectivo',
                   'Efectivo, Pix',                           'Otros',
 'Tarjeta Crédito, Tarjeta Débito',                   'Pix, Efectivo',
           'Otros, Tarjeta Débito',        'Tarjeta Débito, Efectivo',
       'Tarjeta Crédito, Efectivo',  'Tarjeta Débito, Tarjeta Débito',
            'Tarjeta Crédito, Pix',                   'Saldo Cliente',
             'Tarjeta Débito, Pix',            'Pix, Tarjeta Crédito',
                      'Pix, Otros',                      'Debit Card']
Length: 28, dtype: str

In [115]:
sales_detail.loc[sales_detail['payment_type'].str.contains(',', regex=False), 'payment_type'] = 'Multiple'

In [116]:
sales_detail['payment_type'].unique()

<StringArray>
[         'Débito',             'Pix',        'Efectivo',         'Crédito',
               nan,  'Tarjeta Débito', 'Tarjeta Crédito',        'Multiple',
 'Venta a crédito',           'Otros',   'Saldo Cliente',      'Debit Card']
Length: 12, dtype: str

In [117]:
sales_detail.dropna(subset=['payment_type'], inplace=True)

In [118]:
payment_mapping = {
    'Débito': 'Debit Card',
    'Tarjeta Débito': 'Debit Card',
    'Debit Card': 'Debit Card',
    'Crédito': 'Credit Card',
    'Tarjeta Crédito': 'Credit Card',
    'Efectivo': 'Cash',
    'Pix': 'Pix',
    'Otros': 'Meal Voucher',
    'Venta a crédito': 'On Credit',
    'Saldo Cliente': 'On Credit',
    'Multiple': 'Multiple',
}

In [119]:
sales_detail['payment_type'].isna().sum()

np.int64(0)

In [120]:
sales_detail['payment_type'] = sales_detail['payment_type'].replace(payment_mapping)

In [121]:
sales_detail['payment_type'].unique()

<StringArray>
[  'Debit Card',          'Pix',         'Cash',  'Credit Card',
     'Multiple',    'On Credit', 'Meal Voucher']
Length: 7, dtype: str

In [122]:
def clean_kyte_sales(filepath):
    sales_df = pd.read_csv(filepath)
    sales_detail = sales_df[['Date/Time', 'Total', 'Payment Method']]
    sales_detail.rename(columns={'Date/Time': 'sale_time', 'Total': 'amount_sold', 'Payment Method': 'payment_type'}, inplace=True)
    sales_detail['sale_time'] = pd.to_datetime(sales_detail['sale_time'], format='%m/%d/%Y %I:%M %p', errors='coerce')
    sales_detail.loc[sales_detail['payment_type'].str.contains(',', regex=False), 'payment_type'] = 'Multiple'
    
    sales_detail['payment_type'] = sales_detail['payment_type'].replace(payment_mapping)
    return sales_detail

In [123]:
sales_2026 = clean_kyte_sales('../data/raw/kyte/Sales_20260101_20260804.csv')
sales_2026.head()

            sale_time  amount_sold payment_type
0 2026-01-03 11:46:00          9.0         Cash
1 2026-01-03 12:54:00         25.0   Debit Card
2 2026-01-03 13:05:00          6.5         Cash
3 2026-01-03 13:11:00          8.0          Pix
4 2026-01-03 13:29:00          6.5  Credit Card

In [124]:
print(sales_detail.columns)

Index(['sale_time', 'amount_sold', 'payment_type'], dtype='str')

In [125]:
print(sales_2026.columns)

Index(['sale_time', 'amount_sold', 'payment_type'], dtype='str')

In [126]:
sales_detail_full = pd.concat([sales_detail, sales_2026], ignore_index=True)

In [127]:
sales_detail_full.shape

(18270, 3)

In [128]:
sales_detail_full.tail()

                sale_time  amount_sold payment_type
18265 2026-08-03 18:20:00         14.0          Pix
18266 2026-08-03 18:22:00         10.0   Debit Card
18267 2026-08-03 18:38:00         18.0         Cash
18268 2026-08-03 18:44:00         33.0   Debit Card
18269 2026-08-03 18:49:00         10.0          Pix

In [129]:
sales_detail_full.to_csv('../data/processed/sales_detail.csv', index=False)

In [130]:
import os
print(os.listdir('../data/processed'))

['monthly_expenses.csv', 'revenue.csv', 'sales_detail.csv']

In [131]:
sales_2025_raw = pd.read_csv('../data/raw/kyte/Sales_20250101_20260101.csv')
sales_2025_raw['Items Description'].head(20)

0                            1xCopo 150ml, 2xCasquinha
1                                          3xCasquinha
2                                          1xCasquinha
3                 1xChurros de chocolate , 1xCasquinha
4     1xChurros de chocolate , 1xChurros doce de leite
5             1xChurros doce de leite , 1xÁgua sem gás
6                              2xChurros doce de leite
7                               1xChurros de chocolate
8                                          1xCasquinha
9                               1xCascão , 1xCopo 250ml
10                              1xChurros de chocolate
11                              1xChurros de chocolate
12      1xChurros de chocolate , 1xCrepe suíço salgado
13                               1xCrepe suíço salgado
14                                         2xCopo 150ml
15                              1xChurros de chocolate
16                                    1xMilkshake 400ml
17                             1xChurros doce de leite
18                                         1xCasquinha
19                                      1xÁgua com gás
Name: Items Description, dtype: str

In [133]:
items_raw = sales_2025_raw[['Items Description']].copy()

In [134]:
items_raw.head()

                                   Items Description
0                         1xCopo 150ml, 2xCasquinha
1                                       3xCasquinha
2                                       1xCasquinha
3              1xChurros de chocolate , 1xCasquinha
4  1xChurros de chocolate , 1xChurros doce de leite

In [135]:
items_raw['Items Description']= items_raw['Items Description'].str.split(',')

In [138]:
items_raw = items_raw.explode('Items Description', ignore_index=True)

In [139]:
items_raw.head()

         Items Description
0             1xCopo 150ml
1             2xCasquinha
2             3xCasquinha
3             1xCasquinha
4  1xChurros de chocolate

In [141]:
items_raw[['quantity', 'item']] = items_raw['Items Description'].str.split('x', n=1, expand=True)

In [142]:
items_raw.head()

         Items Description quantity                   item
0             1xCopo 150ml        1             Copo 150ml
1             2xCasquinha         2             Casquinha
2             3xCasquinha         3             Casquinha
3             1xCasquinha         1             Casquinha
4  1xChurros de chocolate         1  Churros de chocolate

In [143]:
items_raw['quantity']= pd.to_numeric(items_raw['quantity'], errors='coerce')

In [144]:
items_raw.dtypes

Items Description      str
quantity             int64
item                   str
dtype: object

In [ ]:
items_raw['item'] = items_raw['item'].str.strip()